[package]
name = "basic_plugin"
version = "0.1.0"
authors = ["Andrei Borodaenko <andrei.borodaenko@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
actix = "0.13"
patoka = { path = "../../patoka" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog = "2.7"
